### ISSUE TITLE
Daily work flow

### ISSUE THREAD

**Issue by hilaire** [Cuis-Smalltalk/TheCuisBook#15]
When invoking Cuis with a start up script, Morphic operations may need to be forced for execution with a **self runningWorld doOneCycle** message.
Sort this out and write some more explanations.

https://cuis-smalltalk.github.io/TheCuisBook/Daily-Workflow.html

**Comment by nmingotti** [comment]
As from the mail discussion in the list I post this idea about determining strictly when command line and evironment parameters should/could be run. 

_. **ENV parameters** must be read before anything and must be able to set global variables / Preferences.
. **string parameters** must be executed with high priority, maybe before the World goes up ?
. **script parameters** must be executed when everything else is done._

**Comment by hilaire** [comment]
Mention world do on cycle.
