### ISSUE TITLE
Message ellipseCenterX:y:rx:ry:borderWidth:borderColor:fillColor: no longer exists

### ISSUE THREAD

**Issue by rcpacheco** [Cuis-Smalltalk/TheCuisBook#21]
The message ellipseCenterX:y:rx:ry:borderWidth:borderColor:fillColor:  no longer exists.
There is one that could be used: ellipseCenter:radius:borderWidth:borderColor: fillColor:

There are several references to it:

docs/A-Clock-Morph.html:      ellipseCenterX: 0 y: 0 rx: 100 ry: 100
docs/Back-to-Spacewar_0021-Morphs.html:   canvas ellipseCenterX: 0
docs/Spacewar_0021-Source-Code.html:	canvas ellipseCenterX: 0
docs/Spacewar_0021-Drawing.html:   canvas ellipseCenterX: 0
docs/The-Fundamentals-of-Morph-_0028Solutions_0029.html:   aCanvas ellipseCenterX: 0 y: -70 rx: 3 ry: 3 
en/chapter-50/contents.texinfo:   aCanvas ellipseCenterX: 0 y: -70 rx: 3 ry: 3 
en/chapter-07/contents.texinfo:      ellipseCenterX: 0 y: 0 rx: 100 ry: 100
en/chapter-07/contents.texinfo:   canvas ellipseCenterX: 0
Spacewar!.pck.st:	canvas ellipseCenterX: 0

Also the Clocks sample code  09 in the image  no longer has an implementation similar to the one described in the book. Could be an option to make them similar or mention that there are diferent ways to implement

**Comment by KenDickey** [comment]
Ricardo,

Thank you very much for your detailed comments on the drawing primitive 
changes in TheCuisBook.

As you can probably tell from our late responses we are busy and it 
sometimes takes a while for us to react.

This does not mean that we do not care.  We are amazingly grateful to 
you for careful reading and thoughtful suggestions.

Thanks always for helping us make Cuis even better!

-KenD

**Comment by hilaire** [comment]
Hi Ricardo, 
Thanks to report.
I don't understand your comment:
> Also the Clocks sample code 09 in the image no longer has an implementation similar to the one described in the book.

What is Clocks sample code 09?

The clock morph example was originally written for the book, then later Juan decided to include a variant in the image.

**Comment by rcpacheco** [comment]
Hello, if you go to The Morph class group, then to examples, there are several numbered clases. The 9th corresponds to the clock. It is the same clock as in the book, butch the implementation is different.

Regards 

RPR

**Comment by rcpacheco** [comment]
![image](https://user-images.githubusercontent.com/845725/219380828-96196dc5-51e8-4865-8685-62edd2ba31fa.png)

**Comment by hilaire** [comment]
Yes, that's it. Juan integrated the example from the book in the image and edit it a bit its code.I don't want to rewrite another example.
