### ISSUE TITLE
Spacewar tutorial is impossible to follow

### ISSUE THREAD

**Issue by suhr** [Cuis-Smalltalk/TheCuisBook#28]
In "3.6 Spacewar! States and Behaviors" one creates `SpaceWar` and `SpaceShip` as subclases of Object. The instances have the following variables:

- `centralStar`, `ships`, `torpedoes` for `SpaceWar`
- `name`, `position`, `heading`, `velocity`, `fuel`, `torpedoes`, `mass`, `acceleration` for `SpaceShip`

But in "4.5 SpaceWar! collections" there's the following example:

```smalltalk
SpaceShip>>gravity
"Compute the gravity acceleration vector"
| position |
   position ← self morphPosition.
   ↑ [-10 * self mass * owner starMass / (position r raisedTo: 3) * position]
   on: Error do: [0 @ 0]
```

Cuis does not allow you to create this method, because there's no `owner` variable in `SpaceShip`.

In "5.6 Spacewar!’s methods" you are directly asked to create the following method:

```smalltalk
SpaceWar>>initialize
"We want to capture keyboard and mouse events,
start the game loop(step) and initialize the actors."
super initialize.
   color ← self defaultColor.
   self setProperty: #'handlesKeyboard' toValue: true.
   self setProperty: #'handlesMouseOver:' toValue: true.
   self startSteppingStepTime: self stepTime.
   self initializeActors
```

This does not work either, because there's no `color` in `SpaceWar`.

Spacewar classes become subclasses of `PlacedMorph` only in "6.6 Spacewar! Morphs".

**Comment by stormwatch** [comment]
As you seem to imply in your last sentence
> Spacewar classes become subclasses of PlacedMorph only in "6.6 Spacewar! Morphs".
Until we subclassify accordingly, we can replace `owner` with a reference to the appropiate instance, or even hardcode `8000`.

Moreover, I believe that the problems you raise are the consecuence of a more serious issue: The domain model and the graphical representantion, are completely coupled. So, even if we could follow the tutorial to completion, it would not be very fruitful in my opinion.

Other problems with the current code are: lack of tests, ugly variable and method names, and from the functional point of view, the game desn't support simultaneous key presses: If both players press a key at the same time, only one will be processed.

I like the author's idea of having a single project illustrating and communicating across all the chapters. Maybe we could try to rewrite Spacewar!

**Comment by hilaire** [comment]
Yep, the idea, earlier in the chapter book is to not introduce the Morph object to avoid too much information. These create apparent conflicts later because code redesign with Morph is not discussed either.
In earlier version of the Spacewar we do not have this incoherence, it appeared later with its redesign.
It should be made more coherent but I don't have the time now.

**Comment by hilaire** [comment]
The idea is to keep the illustrating example as short as possible. This is why there is no model or domain model. You will write it differently.
One may want to check out thehttps://github.com/hilaire/CuisApp for such an example with Model View and Presenter

**Comment by hilaire** [comment]
Report any other incoherence you may encounter

**Comment by stormwatch** [comment]
> The idea is to keep the illustrating example of the game as short as possible. Do not forget, this is a book to introduce programming. This is why there is no model or domain model. You will write it differently with a model.

Yes. Maybe I'll try to write a second version, separate from the book. There is always the risk of ending up with a 2D physics game engine, if one gets carried away.

>  One may want to check out the https://github.com/hilaire/CuisApp for such an example with Model, View and Presenter

Thanks for sharing the code; I'll be following it alongside your workshop [Develop end user GUI application with Cuis](https://www.youtube.com/watch?v=E3eDDSPCf7c).
