### ISSUE TITLE
Review figure 7.6 caption

### ISSUE THREAD

**Issue by ngarbezza** [Cuis-Smalltalk/TheCuisBook#3]
Hi! 

I noticed the caption in figure 7.6 does not seem to refer to the image being displayed:

![Screenshot_20210118_192205](https://user-images.githubusercontent.com/519947/104967627-9697f280-59c2-11eb-824c-671d62c47ccb.png)

I'm not sure what exactly should the caption emphasize, if we define the sentence I'm happy submitting the change :)

**Comment by KenDickey** [comment]
On 2021-01-18 22:24, Nahuel Garbezza wrote:

> I noticed the caption in figure 7.6 does not seem to refer to the image 
> being displayed:

Good catch.

I just updated the source.

Hilaire, could you turn the crank and get the web updated?  Thkx!

Thanks for careful reading!
-KenD
