### ISSUE TITLE
HTML rendering of navigation and titles is hard to read

### ISSUE THREAD

**Issue by matta** [Cuis-Smalltalk/TheCuisBook#4]
The rendering of the navigation and section titles in the HTML version is hard for me to read. The choice of a medium-dark green background with black text does not have enough contrast to be clear.

For fun, I ran Google's "Lighthouse" accessibility tool and it complained about the same issue of not enough contrast.

Compare these renderings of similar content:

https://cuis-smalltalk.github.io/TheCuisBook/Preface.html
https://www.gnu.org/software/emacs/manual/html_node/emacs/Screen.html#Screen
https://orgmode.org/manual/TODO-Items.html#TODO-Items

I personally find the Org mode page easiest to read, and the Cuis book page least easy.

Just a simple piece of feedback on an otherwise very enjoyable book so far!

**Comment by hilaire** [comment]
The colour mimic the one of the Cuis Browser. May be not the best choice. I will see how it can be improved.

**Comment by matta** [comment]
Perhaps make the font a little bit larger, omit the white "relief" shadow, and make the background a lighter green.

Here is a screenshot of how the current book renders on HTML on macOS.  Note that for this screenshot I did zoom in to 130% in the browser, and even then the font size was smaller than what Cuis shows in the browser.  I often find myself zooming in these days, so perhaps I am not typical!  :-)

<img width="923" alt="Screen Shot 2021-01-30 at 1 45 15 PM" src="https://user-images.githubusercontent.com/37314/106368865-e13e3680-6301-11eb-89c2-c4fdc8d6d750.png">

**Comment by hilaire** [comment]
I mock up the buttons on the browser not its window title.
When I increased the font (which I tried earlier) in the navigation bar, the bar become way too large with its rightest part not visible in some circumstance.
I improved the chapter title, though. It is more readable now.
Let's see next how we can improve the title bar.

![Capture d’écran de 2021-01-31 11-32-33](https://user-images.githubusercontent.com/1217542/106381432-eca06900-63b8-11eb-8d0d-0c1722b76820.png)

**Comment by hilaire** [comment]
By the way, your font is different on the navigation bar. It should be sans-serif. I don't know the consequence on readability. For me sans is more readable, but it may be different for other people.

**Comment by matta** [comment]
> For me sans is more readable, but it may be different for other people.

I believe the serif -vs- sans-serif issue has more to do with the quality of display than personal preference.  One lower DPI screens, which most people have used for decades, sans-serif looks better. This explains their popularity in computer work, but I think as displays improve we will see more serif fonts used even on the web.

> By the way, your font is different on the navigation bar. It should be sans-serif.

I thought this was a strange thing to say because for me it renders with a serif font on all three browsers on my macOS machine (Safari, Firefox, Chrome). I have not set custom styles in any of these browsers, so I believe the book renders with serif fonts by default.

It seems that Firefox gets a "`font-family: sans`" setting from the body styling CSS:

<img width="348" alt="Screen Shot 2021-02-01 at 8 46 49 AM" src="https://user-images.githubusercontent.com/37314/106489897-1b2a4c80-646a-11eb-88e6-81a2ba7c04b9.png">

But "sans" is not a valid `font-family`: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

When I manually change the body styling to "`font-family: sans-serif`" the book renders with a sans-serif font.

**Comment by hilaire** [comment]
Good catch.

**Comment by matta** [comment]
Thanks for the fixes. I find the headings easy to read now, so I'll close this.
