### ISSUE TITLE
Installation instructions are somewhat hidden in the HTML view

### ISSUE THREAD

**Issue by matta** [Cuis-Smalltalk/TheCuisBook#5]
I am noticing that the installation instructions are somewhat hidden. The hierarchy seems to work better when read linearly (e.g. via PDF) than HTML.  Specifically, "Smalltalk Philosophy" does not suggest that the chapter contains installation instructions and initial "getting started" material.  See See https://cuis-smalltalk.github.io/TheCuisBook/index.html

I might suggest this organization instead:

- Preface
- The Smalltalk Philosophy (merge "Historical Context" with this, making it one essay)
- Getting Started (place Installing, Writing First Scripts, and the first Spacewar! here)

Alternatively, rename "Smalltalk Philosophy" to "Getting Started", and change the chapter's introductory text to suit.  I like this less, because the "philosophy" becomes hidden within "Getting Started", so we've just traded one problem for another.

**Comment by matta** [comment]
I see now that the Info files are split by chapter, so I will refrain from sending a patch or this (since my preferred option is to create a new chapter).

Another idea is to move "The Smalltalk Philosophy" to the Preface chapter.

**Comment by hilaire** [comment]
Yes, getting started should appear as a chapter of its own.

**Comment by KenDickey** [comment]
Rather than changing text order, how about changing the chapter title to something like
 "Philosophy and Getting Started"?  

Or perhaps simply "Beginnings"..

We need to Start Somewhere..
